<div class="row">
    <div class="col-md-12">
	<h1>Lista de Impostos</h1>
	<p>
	    <a href="<?php echo $this->url('imposto', array('action' => 'add')); ?>" class="btn btn-primary">
		Adicionar novo imposto
	    </a>
	</p>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
	<table class="table">
	    <thead>
		<tr class="row">
		    <th class="col-md-5">Nome</th>
		    <th class="col-md-5">Percentual</th>
		    <th class="col-md-2 text-center">#</th>
		</tr>
	    </thead>
	    <tbody>
		<?php foreach ($impostos as $i) : ?>
		    <tr class="row">
			<td class="col-md-5">
			    
			    <?php
			    
				$urlEdit = $this->url('imposto', array(
				    'action' => 'edit',
				    'id' => $this->escapeHtml($i->getId()) 
				));
				
				$urlDelete = $this->url('imposto', array(
				    'action' => 'delete',
				    'id' => $this->escapeHtml($i->getId()) 
				));
			    ?>
			    
			    <a href="<?=$urlEdit?>" title="Clique para editar">
			        <?php echo $this->escapeHtml($i->getNome()); ?>
			    </a>
			    <p class="text-muted">
				<?php echo $this->escapeHtml($i->getDescricao()); ?>
			    </p>
			</td>
			<td class="col-md-5">
			    <?php echo $this->escapeHtml($i->getPercentual()); ?>%
			</td>
			<td class="col-md-2 text-center">
			    <a href="<?=$urlDelete?>" class="btn btn-danger">Deletar</a>
			</td>
		    </tr>    
		<?php endforeach; ?>
	    </tbody>
	</table>
    </div>
</div>


