<div class="jumbotron">
    <h1>Bem vindo ao Glass</h1>
    <h2>O sistema que transparece os impostos.</h2>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Faça uma venda agora !</h3>
            </div>
            <div class="panel-body">
                <p>Utilize esse módulo para realizar vendas</p>
                <p><a class="btn btn-success pull-right" href="/venda">Vendas</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Adicione seus itens e comece a vender !</h3>
            </div>
            <div class="panel-body">
                <p>Manutenção de itens</p>
                <p><a class="btn btn-success pull-right" href="/item">Itens</a></p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Não esqueça de cadastras os impostos...</h3>
            </div>
            <div class="panel-body">
                <p>Matutenção de impostos</p>
                <p><a class="btn btn-success pull-right" href="/imposto">Impostos</a></p>
            </div>
        </div>
    </div>
</div>
